apiVersion: v1
kind: ConfigMap
metadata:
 name: kafka-init
 namespace: default
data:
 init.sh: |
   #!/bin/bash
   ID=$(hostname | awk -F'-' '{print $NF}')
   export KAFKA_CFG_NODE_ID=$ID
   export KAFKA_CFG_ADVERTISED_LISTENERS="INTERNAL://kafka-${ID}.kafka-svc.default.svc.cluster.local:29092,EXTERNAL://localhost:9092"
   exec /entrypoint.sh /run.sh