apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: default
spec:
  containers:
    - name: kafka-client
      image: bitnami/kafka:3.5.1
      command: 
        - "/bin/bash"
        - "-c"
        - "sleep infinity"
